sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"

cache:
  directories:
    $HOME/.npm
    $HOME/.cache # Includes bower cache

before_install:
  - docker-compose build

script:
  - docker-compose up -d
  - docker-compose run app npm test
  - docker-compose stop
