version: '2'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - api
    environment:
      - API_HOST=api
      - API_PORT=8080

  api:
    build: https://github.com/PokemonGoers/PokeData.git#develop
    links:
      - db
    environment:
      - DB_URI=db

  db:
    image: mongo
    volumes:
      - ./db-data:/data/db