sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"

cache:
  directories:
    $HOME/.npm
    $HOME/.cache # Includes bower cache

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - docker-compose run app npm test

after_script:
  - docker-compose stop
